### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/higgs-hunters-facebook#1]
[Build error on Docker Hub](https://hub.docker.com/r/zooniverse/higgs-hunters-facebook/builds/brlb8inrand949eqkwfdswv/):

```
[91m
[0m
[91m/app/node_modules/zooniverse-readymade/node_modules/haw/node_modules/imagemin/index.js:2
[0m
[91mconst fs = require('fs');
^^^^^
[0m
[91mSyntaxError: Use of const in strict mode.
  at Module._compile (module.js:439:25)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/app/node_modules/zooniverse-readymade/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Builder.defaultConfig.optimize.{*,**/*}.jpg (/app/node_modules/zooniverse-readymade/node_modules/haw/lib/default-config.coffee:124:18)
  at Builder._optimizeFile (/app/node_modules/zooniverse-readymade/node_modules/haw/lib/builder.coffee:165:15)
  at /app/node_modules/zooniverse-readymade/node_modules/haw/lib/builder.coffee:1:1
  at replenish (/app/node_modules/zooniverse-readymade/node_modules/haw/node_modules/async/lib/async.js:191:21)
  at /app/node_modules/zooniverse-readymade/node_modules/haw/node_modules/async/lib/async.js:208:15
  at Object.async.eachLimit (/app/node_modules/zooniverse-readymade/node_modules/haw/node_modules/async/lib/async.js:168:12)
  at Builder.optimizeFiles (/app/node_modules/zooniverse-readymade/node_modules/haw/lib/builder.coffee:119:14)
  at /app/node_modules/zooniverse-readymade/node_modules/haw/lib/builder.coffee:43:10
  at /app/node_modules/zooniverse-readymade/node_modules/haw/lib/builder.coffee:102:19
  at Object.oncomplete (fs.js:108:15)
```

**Comment by eatyourgreens** [comment]
Could be caused by haw updating to 0.6.0 https://github.com/zooniverse/haw/commit/ae0dc90dfd2994ec0174881fd56e6f2994061efc

Maybe fix haw to 0.5.1, but we  found that version had stopped installing/building because of the outdated `image-min` module that it depended on.

**Comment by eatyourgreens** [comment]
Caused by an outdated node. Readymade doesn't support node 0.10, as of 1.3 at least. Upgrading to a recent version should fix this.

**Comment by adammcmaster** [comment]
Will this work on Node 7.7?

**Comment by eatyourgreens** [comment]
Should do, but I've only tested that it builds with 6.9.1.
